server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-travel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1101121833
  freemarker:
    settings:
      number_format: 0.##
    suffix: .ftl

aliyun:
  accessKeyId: LTAI5tPKC7kMCZfBJK8t8gxx
  secret: nnPvo3EuztfaPz66JSs8pJ2ABmkVSx
