spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-travel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1101121833
  redis:
    host: 127.0.0.1
aliyun:
  accessKeyId: xxxx
  secret: xxxx
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
