spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-travel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1101121833
  redis:
    host: 127.0.0.1
  data:
    mongodb:
      uri: mongodb://localhost/springboot-travel
aliyun:
  accessKeyId: LTAI5tPKC7kMCZfBJK8t8gxx
  secret: nnPvo3EuztfaPz66JSs8pJ2ABmkVSx
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
